### ISSUE TITLE
Code Widget as Tab next to the userlist

### ISSUE THREAD

**Issue by ghost** [lluachaturbate/CBADK#14]
would it be possible to have the code of the app always visible? putting it to the side or the bottom its not comfortable, also when your load an app the code isnt immediatelly available so you cant set breakpoints. this would be also usefull for the other widgets saving bot vertical and horizontal space

**Comment by lluachaturbate** [comment]
If you click on the code (or any other) widgets titlebar you can actually drag it wherever you want to.
You don't have to place it in the main window at all, it works as a standalone window and by default all your tab and window arrangements will be restored when you restart the ADK.
You can't add them to the CB tabs tho since they are made differently.

I agree that the debugger isn't engaged right away and only on an error might feel weird.
Till i fix it you can use  the standard `debugger;` JS command.
It's simply breakpoint in the code itself.
